# Generated by Django 4.2 on 2023-04-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-modified_at', '-created_at'], 'verbose_name_plural': 'Categories'},
        ),
    ]
