# Generated by Django 4.0.4 on 2022-06-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opt',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
