# Generated by Django 4.0.4 on 2022-06-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_opt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='opt',
            new_name='otp',
        ),
    ]
